### ISSUE TITLE
MoS2 is not a film, currently should become a film, where z is surfacenormal

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida-max-examples#1]

**Comment by AntimoMarrazzo** [comment]
OK, I guess it is just the default when loading a cif file - I am not sure whether we can put OBCs there,,
It's easy to do that with ase on the fly:
a = structure.get_ase()
a.set_pbc([True,True,False])
new_structure = StructureData(ase = a)

**Comment by ltalirz** [comment]
Thanks @AntimoMarrazzo .
I may have misunderstood @broeder-j in the beginning - anyhow, I now had a look as well and
*  the MoS2 cif already *did* contain a monolayer (with a huge spacing of > 20 Angstroms).
* the surface normal was already oriented along z

The only problem were the pbc, which are now set to [True,True,True] for bulk systems and [True,True,False] for monolayers (91222245b437897aadd9228244560df5cbe8e948).
