### ISSUE TITLE
Fleur plugin cannot find xml schema files in the vm

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida-max-examples#4]
This should be solved by an update of aiida-fleur in the vm. The schema files where not 'python module' so far and therefore copied into the site-package dir, if the sourcecode was not cloned, and not installed with -e. Please close this if it works in you case.

**Comment by ltalirz** [comment]
Please let me know, if there is anything I should do at this point. Otherwise I will just wait until the next release of aiida-fleur.

**Comment by broeder-j** [comment]
In aiida-fleur develop there is a MANIFEST now, with that it should work. If it helps you I could make a release the current state

**Comment by ltalirz** [comment]
Yes, that would be helpful.
So far we have only installed released versions of codes & plugins in the VM and I would like to stick with this rule if possible.

**Comment by broeder-j** [comment]
I did a new release of aiida-fleur 0.6.0, a bit rushy but should work

**Comment by ltalirz** [comment]
Thanks!
So, should we switch to using github releases for aiida-fleur or can we continue using pip?

**Comment by broeder-j** [comment]
if possible switch to github release. If not possible I will upload to pypi tomorrow.

**Comment by ltalirz** [comment]
Fixed in 1b000f8614ecfaeb3efc456c192f4400c8e87d4e
