### ISSUE TITLE
fleur example: reuse resources

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-max-examples#5]
@broeder-j  I've merged the pull request, but please reuse the resources from the "options" dictionary for the wc_parameters

By the way, I've just run the TiO2 example on the VM and it seemed to work :-)

**Comment by broeder-j** [comment]
Glad to hear :-).
 I can do so. So far it just uses the wall time. The other options were hardcoded like in run.py .

It is not possible to connect this node as a workchain input, that is clear, right? Only one could write work functions that create the wc_parameter node for the fleur workchains. But this I will not do.
